### ISSUE TITLE
docs: Add installation/usage instructions to README.rst

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/marionette-wrapper#6]
1. need to specify this project is WIP at the moment
2. ~~use rst format for Pypi compatibility~~ Fixed via #8
3. Add install and venv instructions and how to run some tests

**Comment by pdehaan** [comment]
I believe @rpappalax is drafting up something currently in Vim, and he can r? @silne30 to review and merge/modify (assuming rpapa commits a new branch to this repo and not his fork so we can collaborate).
