### ISSUE TITLE
Move all the mozilla-services specific test cases back to services-test repo

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/marionette-wrapper#9]
For example, https://github.com/mozilla-services/services-marionette/tree/master/apps has the following directories:
- /activitystream/
- /pocket/
- /testpilot/

and https://github.com/mozilla-services/services-marionette/tree/master/tests has
- /functional/
  - /activitystream/
  - /experimental/
  - /pocket/
  - /testpilot/
- /integration/

Me thinks we should move the various activitystream apps/tests to somewhere like:
https://github.com/mozilla-services/services-test/activitystream

And that can have an ./app/ and ./functional/ and ./integration/ directory (or whatever).
This lets us keep all the activity-stream tests kept outside the library and together with other tests in services-test repo.

**Comment by pdehaan** [comment]
> @rpapa: i put together a summary of the last proposal we came up w/ from our discussion last time: https://public.etherpad-mozilla.org/p/services-marionette

This was the folder structure I was mentioning up top there. Not sure if it makes sense, or it's the best, but it may work and keep all the code organized nicely without requiring a bunch of code duplication:

> - Keep base classes for services-marionette in services-marionette repo (~200 LOC).
> - Add basic example(s) to repo and tests.
> - Move anything mozilla-services specific out of that repo and back into services-test.
> - Publish module to PyPi.
> - services-test repo clones base class from PyPi and creates page object models by extending from PyPi module.
> 
> ## mozilla-services/services-marionette
> 
> ```
>   apps/
>     __init__.py
>     base.py
>   helpers/
>     __init__.py
>     utils.py
>   tests/*
>   .gitignore
>   README.rst
>   __init__.py
>   setup.py
> ```
> 
> ## mozilla-services/services-test
> 
> ```
>   activity-stream/
>     app/
>       __init__.py
>       app.py
>     functional/
>       __init__.py (needed?)
>       conftest.py
>       test_activitystream_addon_installed.py
>       test_activitystream_verify_activities.py
>     integration/
>       ...
> ```
> 
> ```
>   pocket/
>     app/
>       __init__.py
>       app.py
>     functional/
>       __init__.py
>       conftest.py
>       test_pocket_save_pocket.py
>       test_pocket_signup_fxa.py
>     integration/
>       ...
>     security-test/ (existing stuff)
>       ...
>     e2e-test/ (existing stuff)
>       ...
> ```
> 
> ```
>   testpilot/
>     app/
>       __init__.py
>       app.py
>     functional/
>       __init__.py
>       conftest.py
>       test_testpilot_login.py
>     integration/
>       ...
> ```

**Comment by rpappalax** [comment]
👍

**Comment by pdehaan** [comment]
MVP branch at https://github.com/mozilla-services/services-marionette/tree/mvp-pypi
